NAME = libftprintf.a
CC = gcc -c
FLAGS = -Wall -Werror -Wextra

FILES = 

OBJ = $(FILES:.c=.o)

all: $(NAME)

clean: 
	rm -f $(OBJ) 

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: re all fclean clean 